project:
  type: website
  output-dir: docs

website:
  title: "markie hu styling"
  navbar:
    background: "#f0eeeb"
    foreground: "#57242a"
    pinned: true
    right:
      - href: index.qmd
        text: "CONTACT"
      - href: about.qmd
        text: "ABOUT"
      - href: workwithme.qmd
        text: "WORK WITH ME"
      - href: portfolio.qmd
        text: "TESTIMONIALS"

format:
  html:
    theme: [lux, custom.scss]
    css: custom.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto

editor: visual

